### ISSUE TITLE
binascii.Error: incorrect padding

### ISSUE THREAD

**Issue by Marc-Morcos** [berlincode/sjcl#8]
We get this error when trying to pass something encoded in javascrypt to the python version

![image](https://user-images.githubusercontent.com/30278842/121599452-0f025d00-ca11-11eb-945c-e9388b362030.png)

**Comment by Marc-Morcos** [comment]
it seems to have something to do with https://github.com/berlincode/sjcl/pull/5

**Comment by berlincode** [comment]
Hi Marc. Thanks for creating this issue.

It would be best if you could create a simple test which produces the error above. I simply don't have enough information to fix the issue.

Thanks

**Comment by Marc-Morcos** [comment]
actually It seems to have something to do with the fact that the string is getting altered when sending it as a url request

**Comment by berlincode** [comment]
Sounds reasonable.

Please check this. If your problem is still persists, please open the ticket again. Have a nice day.

**Comment by Marc-Morcos** [comment]
For anyone in the future having this problem, wrap the argument you are sending with javascript with encodeURIComponent()
